### ISSUE TITLE
Adding Facebook?

### ISSUE THREAD

**Issue by onigetoc** [oscarotero/Embed#158]
I just discover that Facebook has their own oembed service.
https://media.fb.com/2015/12/14/improved-embedding-tools-embedded-video-player-api-and-oembed-support/
Could be great adition

**Comment by oscarotero** [comment]
This is already implemented ([example](https://oscarotero.com/embed2/demo/index.php?url=https://www.facebook.com/facebook/videos/10153231379946729/))

Please, check whether the urls work before post an issue.

**Comment by onigetoc** [comment]
Cool, but it do not work for every facebook link. (May be private link but the oembed still work)
ex: https://www.facebook.com/permalink.php?story_fbid=267167410322154&id=100010866918731
Oembed work for all these examples from the Wordpress oembed.
https://github.com/khromov/wp-facebook-oembed/blob/master/wp-facebook-oembed.php

**Comment by oscarotero** [comment]
This link works for me too [example](https://oscarotero.com/embed2/demo/index.php?url=https%3A%2F%2Fwww.facebook.com%2Fpermalink.php%3Fstory_fbid%3D267167410322154%26id%3D100010866918731)

**Comment by onigetoc** [comment]
I just find out that it's better to URLencode the url too not get these error

**Comment by onigetoc** [comment]
It's look like that we can't pass encoded url here
`Embed\Embed::create(get("https%3A%2F%2Fwww.facebook.com%2Fpermalink.php%3Fstory_fbid%3D267167410322154%26id%3D100010866918731"));`

**Comment by oscarotero** [comment]
Fixed. Thanks :)

**Comment by onigetoc** [comment]
mmmm.. still not working on my server and your own.
https://oscarotero.com/embed2/demo/index.php?url=https://www.facebook.com/permalink.php?story_fbid=267167410322154&id=100010866918731

**Comment by oscarotero** [comment]
the new bookmarklet encodes the urls and generate this:
https://oscarotero.com/embed2/demo/index.php?url=https%253A%252F%252Fwww.facebook.com%252Fpermalink.php%253Fstory_fbid%253D267167410322154%2526id%253D100010866918731
that works fine.

**Comment by onigetoc** [comment]
Hi, i talking about a url who is not encoded. It's mean the i will not work with your bookmarklet or with a direct call like this: 
not working: 
https://oscarotero.com/embed2/demo/index.php?url=https://www.facebook.com/permalink.php?story_fbid=267167410322154&id=100010866918731
working
https://oscarotero.com/embed2/demo/index.php?url=https%253A%252F%252Fwww.facebook.com%252Fpermalink.php%253Fstory_fbid%253D267167410322154%2526id%253D100010866918731

**Comment by oscarotero** [comment]
Ok, I'll leave this as is was before, because it was working fine. The problem with non encoded urls is due the ampersand of the facebook url that is treated as a query parameter of the demo url instead a query parameter of the facebook url. I need to fix the bookmarklet to generate good urls (like the submitted form) but it's not a problem of php itself.

**Comment by onigetoc** [comment]
Hi, i revert it back too, yes this is what i though, two ? in the query.
For bookmarkle i just did.

`javascript:(function(){window.open('http://oscarotero.com/embed2/demo/index.php?url='+encodeURIComponent(document.location))})();`

**Comment by oscarotero** [comment]
Yes but, for me, encodeURIComponent doesn't work because sometimes the urls is encoded twice, I don't know why. Anyway, I fixed this in the demo page, appending to the url all query parameters found and now it works fine: https://github.com/oscarotero/Embed/blob/master/demo/index.php#L16
