### ISSUE TITLE
Youtube redirects to cookiewall embed v3.x

### ISSUE THREAD

**Issue by RVXD** [oscarotero/Embed#439]
I use embed3 "version": "v3.4.13".
We are using Embed to embed Youtube videos in SilverStripe, server is on php 7.3.
Since some time embeds no longer work.
It seems the URL is redirected to a cookiewall.

Example in your demo environment, shows it is not working with embed3:
https://oscarotero.com/embed3/demo/index.php?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DR9_eNl5QjmQ

Requested URL:
https://www.youtube.com/watch?v=R9_eNl5QjmQ

Redirected to:
https://consent.youtube.com/m?continue=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DR9_eNl5QjmQ&gl=NL&m=0&pc=yt&uxe=23983172&hl=en&src=1

Hope there is workaround for version 3, the embed seems to be working for version 4.

Embed4 is working:
https://oscarotero.com/embed/demo/index.php?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DR9_eNl5QjmQ&settings=

**Comment by oscarotero** [comment]
This was fixed in v3.4.15 (https://github.com/oscarotero/Embed/issues/434)

**Comment by RVXD** [comment]
Thnx, it's working again.

**Comment by FabianRahm** [comment]
Thanks for the update! However, some videos fail to load and still have the consent modal there.

Example:
https://oscarotero.com/embed/demo/index.php?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DeDPBW-sty9c&settings=

**Comment by RVXD** [comment]
Tried some Belgian, French, Dutch and German youtube video's, that worked properly. Not sure what's the difference with the one you're trying.  
Other videos from the same channel are working:

Not working from german channel:
https://www.youtube.com/watch?v=eDPBW-sty9c
Working from same channel:
https://www.youtube.com/watch?v=zDEveu4C_EY

Could it be some kind of server side caching?

**Comment by RVXD** [comment]
The video you were testing does not allow embedding.
Check:
https://www.youtube.com/oembed?scheme=https&url=https://www.youtube.com/watch?v=eDPBW-sty9c
Probably the user has restricted embedding for this specific video.

**Comment by FabianRahm** [comment]
Wow thanks @RVXD this is beyond embarrassing and we should have caught that earlier.
